trab1: trab1.cpp
	g++ -o trab1 trab1.cpp -g -lglut -lGLU -lm -lGL -Wall

trab2: trab2.cpp
	g++ -o trab2 trab2.cpp -g -lglut -lGLU -lm -lGL -Wall

trab3: trab3.cpp
	g++ -o trab3 trab3.cpp -g -lglut -lGLU -lm -lGL -Wall
